/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;

/**
 *
 * @author Familia
 */
public class GUIAdmin extends javax.swing.JFrame {

    /**
     * Creates new form GUIAdmin
     */
    public GUIAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Tools&Stuff: Adminstrador de Bodega V0.01");  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        desconectar = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        listainst = new javax.swing.JMenuItem();
        selctinst = new javax.swing.JMenuItem();
        reginst = new javax.swing.JMenuItem();
        actuinst = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        listprod = new javax.swing.JMenuItem();
        ingprod = new javax.swing.JMenuItem();
        salprod = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        listper = new javax.swing.JMenuItem();
        regper = new javax.swing.JMenuItem();
        actper = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        regus = new javax.swing.JMenuItem();
        actus = new javax.swing.JMenuItem();
        infr = new javax.swing.JMenu();
        INFor = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpadm = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Inicio");

        desconectar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        desconectar.setMnemonic('o');
        desconectar.setText("Desconectar");
        desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desconectarActionPerformed(evt);
            }
        });
        fileMenu.add(desconectar);

        Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Salir.setMnemonic('x');
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        fileMenu.add(Salir);

        menuBar.add(fileMenu);

        jMenu1.setText("Instalaciones");

        listainst.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        listainst.setMnemonic('s');
        listainst.setText("Lista de Instalaciones");
        listainst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listainstActionPerformed(evt);
            }
        });
        jMenu1.add(listainst);

        selctinst.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        selctinst.setText("Seleccion de Instalacion");
        selctinst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selctinstActionPerformed(evt);
            }
        });
        jMenu1.add(selctinst);

        reginst.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        reginst.setText("Registro de Instalacion");
        reginst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reginstActionPerformed(evt);
            }
        });
        jMenu1.add(reginst);

        actuinst.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        actuinst.setMnemonic('a');
        actuinst.setText("Actualizacion de Instalacion");
        actuinst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actuinstActionPerformed(evt);
            }
        });
        jMenu1.add(actuinst);

        menuBar.add(jMenu1);

        editMenu.setMnemonic('e');
        editMenu.setText("Productos");

        listprod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        listprod.setMnemonic('t');
        listprod.setText("Lista de Productos");
        listprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listprodActionPerformed(evt);
            }
        });
        editMenu.add(listprod);

        ingprod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        ingprod.setText("Ingreso de Producto");
        ingprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingprodActionPerformed(evt);
            }
        });
        editMenu.add(ingprod);

        salprod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        salprod.setMnemonic('d');
        salprod.setText("Salida de Producto");
        salprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salprodActionPerformed(evt);
            }
        });
        editMenu.add(salprod);

        menuBar.add(editMenu);

        jMenu2.setText("Personal");

        listper.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        listper.setMnemonic('y');
        listper.setText("Lista de Personal");
        listper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listperActionPerformed(evt);
            }
        });
        jMenu2.add(listper);

        regper.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        regper.setMnemonic('p');
        regper.setText("Registro de Personal");
        regper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regperActionPerformed(evt);
            }
        });
        jMenu2.add(regper);

        actper.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        actper.setMnemonic('y');
        actper.setText("Actualizacion de Personal");
        actper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actperActionPerformed(evt);
            }
        });
        jMenu2.add(actper);

        menuBar.add(jMenu2);

        jMenu3.setText("Usuarios");

        regus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        regus.setMnemonic('y');
        regus.setText("Registro de Usuarios");
        regus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regusActionPerformed(evt);
            }
        });
        jMenu3.add(regus);

        actus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        actus.setMnemonic('y');
        actus.setText("Actualizar Usuarios");
        actus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actusActionPerformed(evt);
            }
        });
        jMenu3.add(actus);

        menuBar.add(jMenu3);

        infr.setText("Registro");

        INFor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        INFor.setMnemonic('y');
        INFor.setText("Informe Mensual General");
        INFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INForActionPerformed(evt);
            }
        });
        infr.add(INFor);

        menuBar.add(infr);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        helpadm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        helpadm.setMnemonic('c');
        helpadm.setText("Contenidos");
        helpadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpadmActionPerformed(evt);
            }
        });
        helpMenu.add(helpadm);

        about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        about.setMnemonic('a');
        about.setText("Acerca de...");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        helpMenu.add(about);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        GUISalir ds = new GUISalir();

        this.desktopPane.add("GUISalir", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_SalirActionPerformed

    private void desconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desconectarActionPerformed

        GUILogout ds = new GUILogout();

        this.desktopPane.add("GUILogout", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_desconectarActionPerformed

    private void actuinstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actuinstActionPerformed
        GUIUpdateInstalacion ds = new GUIUpdateInstalacion();

        this.desktopPane.add("GUIUpdateInstalacion", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_actuinstActionPerformed

    private void listperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listperActionPerformed
        GUIListaPersonal ds = new GUIListaPersonal();

        this.desktopPane.add("GUIListaPersonal", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_listperActionPerformed

    private void actperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actperActionPerformed
        GUIUpdatePersonal ds = new GUIUpdatePersonal();

        this.desktopPane.add("GUIUpdatePersonal", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_actperActionPerformed

    private void regusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regusActionPerformed
        GUIRegistrarUsuario ds = new GUIRegistrarUsuario();

        this.desktopPane.add("GUIRegistrarUsuario", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_regusActionPerformed

    private void actusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actusActionPerformed
        GUIUpdateUsuario ds = new GUIUpdateUsuario();

        this.desktopPane.add("GUIUpdateUsuario", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_actusActionPerformed

    private void INForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INForActionPerformed
        GUIInforme ds = new GUIInforme();

        this.desktopPane.add("GUIInforme", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_INForActionPerformed

    private void helpadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpadmActionPerformed
        GUIAyuda ds = new GUIAyuda();

        this.desktopPane.add("GUIAyuda", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_helpadmActionPerformed

    private void selctinstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selctinstActionPerformed
        GUISeleccionInstalacion ds = new GUISeleccionInstalacion();

        this.desktopPane.add("GUISeleccionInstalacion", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_selctinstActionPerformed

    private void reginstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reginstActionPerformed
        GUIRegistroInstalacion ds = new GUIRegistroInstalacion();

        this.desktopPane.add("GUIRegistroInstalacion", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_reginstActionPerformed

    private void listprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listprodActionPerformed
        GUIInventario ds = new GUIInventario();

        this.desktopPane.add("GUIInventario", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_listprodActionPerformed

    private void ingprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingprodActionPerformed
        GUIRegistrarProducto ds = new GUIRegistrarProducto();

        this.desktopPane.add("GUIRegistrarProducto", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_ingprodActionPerformed

    private void salprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salprodActionPerformed
        GUISalidaProducto ds = new GUISalidaProducto();

        this.desktopPane.add("GUISalidaProducto", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_salprodActionPerformed

    private void regperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regperActionPerformed
        GUIRegistroPersonal ds = new GUIRegistroPersonal();

        this.desktopPane.add("GUIRegistroPersonal", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_regperActionPerformed

    private void listainstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listainstActionPerformed
        GUIListaInstalacion ds = new GUIListaInstalacion();

        this.desktopPane.add("GUIListaInstalacion", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_listainstActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        GUIAbout ds = new GUIAbout();

        this.desktopPane.add("GUIAbout", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();

        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);

        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem INFor;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem actper;
    private javax.swing.JMenuItem actuinst;
    private javax.swing.JMenuItem actus;
    private javax.swing.JMenuItem desconectar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpadm;
    private javax.swing.JMenu infr;
    private javax.swing.JMenuItem ingprod;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem listainst;
    private javax.swing.JMenuItem listper;
    private javax.swing.JMenuItem listprod;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem reginst;
    private javax.swing.JMenuItem regper;
    private javax.swing.JMenuItem regus;
    private javax.swing.JMenuItem salprod;
    private javax.swing.JMenuItem selctinst;
    // End of variables declaration//GEN-END:variables

}
